version: '3.8'

services:
  postgres:
    container_name: postgres-rest
    image: postgres:13.0-alpine
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - .env
    networks: # Добавьте определение сети для контейнера PostgreSQL
      - my_network  # Имя сети, например, my_network

  resto_back:
    container_name: resto_back
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    tty: true
    ports:
      - "8000:8000"
    networks:  # Добавьте определение сети для контейнера resto_back
      - my_network  # Имя сети, например, my_network

networks:  # Определение сети my_network
  my_network:
    driver: bridge



volumes:
  postgres_data:

