version: '3.8'

services:
  postgres:
    container_name: postgres-rest
    image: postgres:15.1-alpine
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - test_network

  test:
    build:
      dockerfile: ./Dockerfile_tests
    env_file:
      - .env
    container_name: test
    volumes:
      - .:/app
    restart: always
    tty: true
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - test_network

networks:
  test_network:
    driver: bridge

volumes:
  postgres_data: