version: '3.8'

services:
  postgres:
    container_name: postgres-rest
    image: postgres:15.1-alpine
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - my_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d","postgres-rest" ]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s

  resto_back:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resto_back
    depends_on:
       postgres:
         condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    tty: true
    ports:
      - "8000:8000"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data: