version: '3.8'

services:
  postgres:
    container_name: postgres-rest
    image: postgres:13.0-alpine
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - my_network

  resto_back:
    image: markkryl93/resto_back:latest
    container_name: resto_back
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    tty: true
    ports:
      - "8000:8000"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data: