version: '3.8'

services:
  postgres:
    image: postgres:15.1-alpine
    container_name: tests_db
    command: -p 6000
    expose:
      - 6000
    env_file:
      - .env
    environment:
      - LANG=en_US.utf8
      - LC_ALL=en_US.utf8
    networks:
      - test_network

  test:
    build:
      dockerfile: ./Dockerfile_tests
    env_file:
      - .env
    container_name: test
    volumes:
      - .:/app
    tty: true
    depends_on:
       - postgres
    networks:
      - test_network
    command: pytest

networks:
  test_network:
