"""initial migration

Revision ID: 748f3550acdc
Revises:
Create Date: 2023-08-07 00:23:16.507614

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '748f3550acdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
                    sa.Column('title', sa.TEXT(), nullable=False),
                    sa.Column('description', sa.TEXT(), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('title')
                    )
    op.create_table('submenus',
                    sa.Column('title', sa.TEXT(), nullable=False),
                    sa.Column('description', sa.TEXT(), nullable=False),
                    sa.Column('menu_id', sa.UUID(), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('title'),
                    sa.UniqueConstraint('title', 'menu_id')
                    )
    op.create_table('dishes',
                    sa.Column('title', sa.TEXT(), nullable=False),
                    sa.Column('description', sa.TEXT(), nullable=False),
                    sa.Column('price', sa.Numeric(precision=7, scale=2), nullable=False),
                    sa.Column('submenu_id', sa.UUID(), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['submenu_id'], ['submenus.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('title')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dishes')
    op.drop_table('submenus')
    op.drop_table('menus')
    # ### end Alembic commands ###
